<?php
/**
 * Admin view for managing SaaS products.
 * Expects $action, $products (array), and optionally $product_data (array) to be passed from the controller.
 */

// Example: Data that would be passed by a controller
$action = $action ?? 'list'; // 'list', 'add', 'edit'
$products = $products ?? []; // Array of product objects/arrays for the list view
$product_data = $product_data ?? [ // Data for the add/edit form
    'id' => '',
    'name' => '',
    'description' => '',
    'access_level' => 'basic', // Default
    'features' => [''], // Default with one empty feature
    'enabled' => true // Default
];
$feedback_message = $feedback_message ?? null; // For displaying success/error messages

// --- URLs (Example data from controller or router) ---
$add_product_url = '/admin/products?action=add';
$products_list_url = '/admin/products';
$save_product_action_url = '/admin/products/save'; // Target for form submission
// Note: Edit and delete URLs will be constructed dynamically in the list table.

// --- Helper function for selected attribute (alternative to WordPress selected()) ---
function select_attr($current_value, $option_value) {
    return $current_value == $option_value ? 'selected' : '';
}
?>

<div class="wrap mifeco-saas-admin-wrap">
    <div class="mifeco-saas-admin-header">
        <h1>SaaS Products Management</h1>
        <?php if ($action === 'list'): ?>
            <a href="<?php echo htmlspecialchars($add_product_url); ?>" class="button button-primary">
                Add New Product
            </a>
        <?php endif; ?>
    </div>

    <?php if ($feedback_message): ?>
        <div class="notice notice-<?php echo htmlspecialchars($feedback_message['type'] ?? 'info'); ?> is-dismissible">
            <p><?php echo htmlspecialchars($feedback_message['text'] ?? ''); ?></p>
        </div>
    <?php endif; ?>

    <?php
    if ($action === 'add' || $action === 'edit') :
        $form_title = ($action === 'edit') ? 'Edit Product' : 'Add New Product';
    ?>
        <div class="mifeco-product-form-container">
            <h2><?php echo $form_title; ?></h2>
            <form method="post" action="<?php echo htmlspecialchars($save_product_action_url); ?>" class="mifeco-product-form">
                <!-- A CSRF token would be generated by the framework/session management -->
                <input type="hidden" name="_csrf_token" value="your_csrf_token_here">
                <input type="hidden" name="product_id" value="<?php echo htmlspecialchars($product_data['id'] ?? ''); ?>">

                <div class="mifeco-form-section">
                    <h3>Product Information</h3>

                    <div class="mifeco-form-field">
                        <label for="product_name">Product Name</label>
                        <input type="text" id="product_name" name="product_name" value="<?php echo htmlspecialchars($product_data['name'] ?? ''); ?>" required>
                    </div>

                    <div class="mifeco-form-field">
                        <label for="product_description">Description</label>
                        <textarea id="product_description" name="product_description" rows="4"><?php echo htmlspecialchars($product_data['description'] ?? ''); ?></textarea>
                    </div>

                    <div class="mifeco-form-field">
                        <label for="product_access_level">Access Level</label>
                        <select id="product_access_level" name="product_access_level">
                            <option value="basic" <?php echo select_attr($product_data['access_level'] ?? '', 'basic'); ?>>Basic Plan</option>
                            <option value="premium" <?php echo select_attr($product_data['access_level'] ?? '', 'premium'); ?>>Premium Plan</option>
                            <option value="enterprise" <?php echo select_attr($product_data['access_level'] ?? '', 'enterprise'); ?>>Enterprise Plan</option>
                        </select>
                    </div>

                    <div class="mifeco-form-field">
                        <label for="product_enabled">Status</label>
                        <select id="product_enabled" name="product_enabled">
                            <option value="1" <?php echo select_attr($product_data['enabled'] ?? true, true); ?>>Enabled</option>
                            <option value="0" <?php echo select_attr($product_data['enabled'] ?? true, false); ?>>Disabled</option>
                        </select>
                    </div>
                </div>

                <div class="mifeco-form-section">
                    <h3>Product Features</h3>
                    <div id="mifeco-plan-features-list">
                        <?php
                        $features = $product_data['features'] ?? [''];
                        if (empty($features)) $features = ['']; // Ensure at least one input
                        foreach ($features as $index => $feature) :
                        ?>
                            <div class="mifeco-plan-feature-item">
                                <input type="text" name="product_features[]" value="<?php echo htmlspecialchars($feature); ?>" placeholder="Enter feature">
                                <button type="button" class="button mifeco-remove-feature">Remove</button>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <button type="button" class="button mifeco-add-feature-btn">Add Feature</button>
                </div>

                <div class="mifeco-form-actions">
                    <button type="submit" class="button button-primary">Save Product</button>
                    <a href="<?php echo htmlspecialchars($products_list_url); ?>" class="button">Cancel</a>
                </div>
            </form>
        </div>
    <?php else : // Default: List products ?>
        <div class="mifeco-products-list-container">
            <table class="wp-list-table widefat fixed striped mifeco-saas-products-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Access Level</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (empty($products)) {
                        echo '<tr><td colspan="4">No products found.</td></tr>';
                    } else {
                        foreach ($products as $product) {
                            $product_id = htmlspecialchars($product['id'] ?? '');
                            $edit_url = '/admin/products?action=edit&id=' . $product_id;
                            // For delete, usually a POST request with CSRF, or a GET to a confirmation page
                            $delete_url = '/admin/products/delete?id=' . $product_id . '&_csrf_token=your_csrf_token_here';

                            $access_level_display = 'Unknown';
                            if (isset($product['access_level'])) {
                                switch ($product['access_level']) {
                                    case 'basic': $access_level_display = 'Basic Plan'; break;
                                    case 'premium': $access_level_display = 'Premium Plan'; break;
                                    case 'enterprise': $access_level_display = 'Enterprise Plan'; break;
                                    default: $access_level_display = ucfirst(htmlspecialchars($product['access_level']));
                                }
                            }

                            $status_display = ($product['enabled'] ?? false) ?
                                '<span class="mifeco-status-active">Active</span>' :
                                '<span class="mifeco-status-inactive">Inactive</span>';

                            echo '<tr>';
                            echo '<td><strong>' . htmlspecialchars($product['name'] ?? 'N/A') . '</strong></td>';
                            echo '<td>' . htmlspecialchars($access_level_display) . '</td>';
                            echo '<td>' . $status_display . '</td>';
                            echo '<td class="mifeco-saas-product-actions">';
                            echo '<a href="' . htmlspecialchars($edit_url) . '" class="button button-small">Edit</a> ';
                            echo '<a href="' . htmlspecialchars($delete_url) . '" class="button button-small button-danger" onclick="return confirm(\'Are you sure you want to delete this product?\')">Delete</a>';
                            echo '</td>';
                            echo '</tr>';
                        }
                    }
                    ?>
                </tbody>
            </table>
        </div>
    <?php endif; ?>
</div>

<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function() {
    // Add feature button
    const addFeatureBtn = document.querySelector('.mifeco-add-feature-btn');
    if (addFeatureBtn) {
        addFeatureBtn.addEventListener('click', function() {
            const featureList = document.getElementById('mifeco-plan-features-list');
            if (featureList) {
                const featureItem = document.createElement('div');
                featureItem.classList.add('mifeco-plan-feature-item');

                const featureInput = document.createElement('input');
                featureInput.type = 'text';
                featureInput.name = 'product_features[]';
                featureInput.placeholder = 'Enter feature';

                const removeButton = document.createElement('button');
                removeButton.type = 'button';
                removeButton.classList.add('button', 'mifeco-remove-feature');
                removeButton.textContent = 'Remove';

                featureItem.appendChild(featureInput);
                featureItem.appendChild(removeButton);
                featureList.appendChild(featureItem);
            }
        });
    }

    // Remove feature (event delegation for dynamically added items)
    const featureList = document.getElementById('mifeco-plan-features-list');
    if (featureList) {
        featureList.addEventListener('click', function(event) {
            if (event.target && event.target.classList.contains('mifeco-remove-feature')) {
                event.target.closest('.mifeco-plan-feature-item').remove();
            }
        });
    }
});
</script>

<style>
/* Basic styling for admin views - can be moved to a separate CSS file */
.mifeco-saas-admin-wrap { margin-top: 20px; }
.mifeco-saas-admin-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
.mifeco-saas-admin-header h1 { margin: 0; }
.mifeco-product-form-container, .mifeco-products-list-container { background: #fff; padding: 20px; border: 1px solid #ccd0d4; }
.mifeco-form-section { margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid #eee; }
.mifeco-form-section:last-child { border-bottom: none; }
.mifeco-form-field { margin-bottom: 15px; }
.mifeco-form-field label { display: block; margin-bottom: 5px; font-weight: bold; }
.mifeco-form-field input[type="text"],
.mifeco-form-field textarea,
.mifeco-form-field select { width: 100%; padding: 8px; border: 1px solid #ddd; box-sizing: border-box; }
.mifeco-plan-feature-item { display: flex; margin-bottom: 10px; }
.mifeco-plan-feature-item input[type="text"] { flex-grow: 1; margin-right: 10px; }
.mifeco-form-actions { margin-top: 20px; }
.button { padding: 8px 15px; text-decoration: none; border-radius: 3px; cursor: pointer; }
.button-primary { background-color: #0073aa; color: white; border: 1px solid #0073aa; }
.button-danger { background-color: #d63638; color: white; border: 1px solid #d63638; }
.mifeco-status-active { color: green; font-weight: bold; }
.mifeco-status-inactive { color: red; }
.notice { padding: 10px; margin-bottom: 15px; border-left-width: 4px; border-left-style: solid; }
.notice-info { border-left-color: #0073aa; background: #f0f6fc; }
.notice-success { border-left-color: #46b450; background: #f0f8f1; }
.notice-error { border-left-color: #d63638; background: #fdf1f1; }
.wp-list-table { border-collapse: collapse; width: 100%; }
.wp-list-table th, .wp-list-table td { padding: 10px; border: 1px solid #ddd; text-align: left; }
.wp-list-table th { background-color: #f5f5f5; }
</style>
